Vagrant.configure(2) do |config|

  # CentOS 6
  config.vm.define "certbot-el6" do |centos6|
    centos6.vm.box = "geerlingguy/centos6"
    centos6.vm.hostname = "certbot-centos6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "certbot-el6"
      # vbox.cpus = 1
      # vbox.memory = 128
    end
  end

  # CentOS 7
  config.vm.define "certbot-el7" do |centos7|
    centos7.vm.box = "geerlingguy/centos7"
    centos7.vm.hostname = "certbot-centos7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "certbot-el7"
      # vbox.cpus = 1
      # vbox.memory = 128
    end
  end

  # Ubuntu 14.04
  config.vm.define "certbot-ub14" do |ub14|
    ub14.vm.box = "geerlingguy/ubuntu1404"
    ub14.vm.hostname = "certbot-ub14"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "certbot-ub14"
      # vbox.cpus = 1
      # vbox.memory = 128
    end
  end

  # Ubuntu 16.04
  config.vm.define "certbot-ub16" do |ub16|
    ub16.vm.box = "geerlingguy/ubuntu1604"
    ub16.vm.hostname = "certbot-ub16"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "certbot-ub16"
      # vbox.cpus = 1
      vbox.memory = 256
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
